name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update pip and setuptools
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools
      - name: Install dependencies
        run: |
          python -m pip install flake8
      - name: Lint with flake8
        run: |
          flake8
